CREATE TABLE IF NOT EXISTS domain_trafik (
  domain_id BIGINT UNSIGNED NOT NULL,
  yil_ay CHAR(7) NOT NULL,
  bytes BIGINT NOT NULL DEFAULT 0,
  guncelleme TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (domain_id, yil_ay),
  KEY ix_trafik_ay (yil_ay)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS domain_trafik_imlec (
  domain_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  ofset BIGINT NOT NULL DEFAULT 0,
  boyut BIGINT NOT NULL DEFAULT 0,
  guncelleme TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
