CREATE TABLE IF NOT EXISTS wp_bakim (
  domain_id BIGINT UNSIGNED NOT NULL,
  dizin VARCHAR(255) NOT NULL DEFAULT '/',
  aktif TINYINT(1) NOT NULL DEFAULT 0,
  guncelleme TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (domain_id, dizin),
  CONSTRAINT fk_wp_bakim_domain FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
